from django.urls import path

from Main.views.api import (
    RealtimeSearch,
    alert_rule_item,
    alert_rules,
    complex_market_data,
    convert_watch_item_to_inventory,
    delete_market_data,
    get_market_data,
    get_popular_words,
    get_search_words,
    inventory_item,
    inventory_items,
    inventory_profit_simulation,
    notification_item,
    notifications,
    notifications_read_all,
    perform_search,
    prediction_market,
    purchase_budget,
    purchase_cost_settings,
    run_saved_search,
    saved_search_item,
    saved_searches,
    seller_listing_item,
    seller_listing_refresh,
    seller_listing_sale,
    seller_listing_snapshots,
    seller_listings,
    seller_outcomes,
    update_market_data,
    watchlist,
    watchlist_item,
    watchlist_snapshots,
)
from Main.views.developer import developer_dashboard
from Main.views.urls import (
    Deep_Analysis,
    Deep_Analysis_now,
    Yahuoku,
    Yahuoku_history,
    Yahuoku_now,
    Yahuoku_prediction,
    alert_rules_page,
    index,
    introduction,
    market_search,
    notifications_page,
    seller_management,
    seller_outcomes_page,
)

urlpatterns = [
    path("api/v1/cost-settings", purchase_cost_settings, name="purchase_cost_settings"),
    path(
        "api/v1/watch-items/<int:item_id>/purchase-budget", purchase_budget, name="purchase_budget"
    ),
    path("", index, name="index"),
    path("yahuoku", Yahuoku, name="yahuoku"),
    path("yahuoku_now", Yahuoku_now, name="yahuoku_now"),
    path("yahuoku_history", Yahuoku_history, name="yahuoku_history"),
    path("market-search", market_search, name="market_search"),
    path("Deep_Analysis", Deep_Analysis, name="Deep_Analysis"),
    path("Deep_Analysis_now", Deep_Analysis_now, name="Deep_Analysis_now"),
    path("Yahuoku_prediction", Yahuoku_prediction, name="Yahuoku_prediction"),
    path("introduction", introduction, name="introduction"),
    path("developer/", developer_dashboard, name="developer_dashboard"),
    path("seller-management", seller_management, name="seller_management"),
    path("seller-outcomes", seller_outcomes_page, name="seller_outcomes_page"),
    path("notifications", notifications_page, name="notifications_page"),
    path("alerts", alert_rules_page, name="alert_rules_page"),
    path("perform_search", perform_search, name="perform_search"),
    path("RealtimeSearch", RealtimeSearch, name="RealtimeSearch"),
    path("get_search_words", get_search_words, name="get_search_words"),
    path("get_market_data", get_market_data, name="get_market_data"),
    path("update_market_data", update_market_data, name="update_market_data"),
    path("delete_market_data", delete_market_data, name="delete_market_data"),
    path("complex_market_data", complex_market_data, name="complex_market_data"),
    path("prediction_market", prediction_market, name="prediction_market"),
    path("get_popular_words", get_popular_words, name="get_popular_words"),
    path("watchlist", watchlist, name="watchlist"),
    path("watchlist/<int:item_id>", watchlist_item, name="watchlist_item"),
    path(
        "watchlist/<int:item_id>/snapshots",
        watchlist_snapshots,
        name="watchlist_snapshots",
    ),
    path("api/v1/saved-searches", saved_searches, name="saved_searches"),
    path("api/v1/notifications", notifications, name="notifications"),
    path("api/v1/alert-rules", alert_rules, name="alert_rules"),
    path(
        "api/v1/alert-rules/<int:alert_rule_id>",
        alert_rule_item,
        name="alert_rule_item",
    ),
    path(
        "api/v1/notifications/read-all",
        notifications_read_all,
        name="notifications_read_all",
    ),
    path(
        "api/v1/notifications/<int:notification_id>",
        notification_item,
        name="notification_item",
    ),
    path("api/v1/inventory-items", inventory_items, name="inventory_items"),
    path("api/v1/seller-listings", seller_listings, name="seller_listings"),
    path("api/v1/seller-outcomes", seller_outcomes, name="seller_outcomes"),
    path(
        "api/v1/seller-listings/<int:listing_id>", seller_listing_item, name="seller_listing_item"
    ),
    path(
        "api/v1/seller-listings/<int:listing_id>/refresh",
        seller_listing_refresh,
        name="seller_listing_refresh",
    ),
    path(
        "api/v1/seller-listings/<int:listing_id>/sale",
        seller_listing_sale,
        name="seller_listing_sale",
    ),
    path(
        "api/v1/seller-listings/<int:listing_id>/snapshots",
        seller_listing_snapshots,
        name="seller_listing_snapshots",
    ),
    path(
        "api/v1/inventory-items/<int:item_id>",
        inventory_item,
        name="inventory_item",
    ),
    path(
        "api/v1/inventory-items/<int:item_id>/profit-simulation",
        inventory_profit_simulation,
        name="inventory_profit_simulation",
    ),
    path(
        "api/v1/watch-items/<int:watch_item_id>/convert-to-inventory",
        convert_watch_item_to_inventory,
        name="convert_watch_item_to_inventory",
    ),
    path(
        "api/v1/saved-searches/<int:saved_search_id>",
        saved_search_item,
        name="saved_search_item",
    ),
    path(
        "api/v1/saved-searches/<int:saved_search_id>/run",
        run_saved_search,
        name="run_saved_search",
    ),
]
