# Generated by Django 5.0.1 on 2024-01-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MYschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskName', models.TextField()),
                ('StartTime', models.TimeField()),
                ('Endtime', models.TimeField()),
                ('Day', models.DateField()),
                ('ElapsedTime', models.TimeField()),
                ('DeleteFlag', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ResultSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskName', models.TextField()),
                ('StartTime', models.TimeField()),
                ('Endtime', models.TimeField()),
                ('Day', models.DateField()),
                ('ElapsedTime', models.TimeField()),
                ('DeleteFlag', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SelectDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Adress', models.TextField()),
                ('Mailtext', models.TextField()),
                ('Objective', models.TextField()),
                ('Subject', models.TextField()),
                ('Todays', models.TextField()),
                ('DeleteFlag', models.TextField()),
            ],
        ),
    ]
