# Generated by Django 5.0.1 on 2024-01-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='scraping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SearchWord', models.TextField()),
                ('SearchDay', models.TextField()),
                ('Bidding', models.TextField()),
                ('EndPrice', models.IntegerField()),
                ('StartPrice', models.IntegerField()),
                ('Name', models.TextField()),
                ('URL', models.TextField()),
            ],
        ),
    ]
