# Generated by Django 5.1.4 on 2025-05-17 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_delete_myschedule_delete_resultschedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelectDestination',
        ),
    ]
