# Generated by Django 5.1.4 on 2025-05-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_delete_selectdestination'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_code', models.CharField(help_text='エラーコード', max_length=50)),
                ('error_message', models.TextField(help_text='エラーメッセージ')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='発生時刻')),
                ('file_path', models.CharField(blank=True, help_text='発生ファイルパス', max_length=255)),
                ('line_number', models.IntegerField(blank=True, help_text='発生行番号', null=True)),
            ],
            options={
                'verbose_name': 'エラーログ',
                'verbose_name_plural': 'エラーログ一覧',
            },
        ),
    ]
