# Generated by Django 5.2.1 on 2025-06-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_errorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='searchwordlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=255)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '検索ワード履歴',
                'verbose_name_plural': '検索ワード履歴',
            },
        ),
        migrations.AlterModelOptions(
            name='scraping',
            options={'verbose_name': '商品詳細', 'verbose_name_plural': '検索結果'},
        ),
        migrations.AlterField(
            model_name='scraping',
            name='Bidding',
            field=models.TextField(help_text='入札数'),
        ),
        migrations.AlterField(
            model_name='scraping',
            name='EndPrice',
            field=models.IntegerField(help_text='終了価格'),
        ),
        migrations.AlterField(
            model_name='scraping',
            name='Name',
            field=models.TextField(help_text='商品名'),
        ),
        migrations.AlterField(
            model_name='scraping',
            name='SearchDay',
            field=models.TextField(help_text='検索日'),
        ),
        migrations.AlterField(
            model_name='scraping',
            name='SearchWord',
            field=models.TextField(help_text='検索ワード'),
        ),
        migrations.AlterField(
            model_name='scraping',
            name='StartPrice',
            field=models.IntegerField(help_text='開始価格'),
        ),
        migrations.AlterField(
            model_name='scraping',
            name='URL',
            field=models.TextField(help_text='URL'),
        ),
    ]
