# Generated by Django 6.1 on 2026-09-03 03:19

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0016_inventory_phase3a"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SellerListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("external_listing_id", models.CharField(db_index=True, max_length=255)),
                ("url", models.CharField(max_length=1000)),
                ("name", models.TextField()),
                ("condition", models.CharField(db_index=True, default="unknown", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "登録済み"),
                            ("active", "出品中"),
                            ("ended", "終了"),
                            ("sold", "落札済み"),
                            ("cancelled", "見送り"),
                            ("relist", "再出品待ち"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("observed_status", models.CharField(default="unknown", max_length=20)),
                ("start_price", models.PositiveBigIntegerField(default=0)),
                ("current_price", models.PositiveBigIntegerField(default=0)),
                ("buyout_price", models.PositiveBigIntegerField(blank=True, null=True)),
                ("bidding", models.PositiveIntegerField(default=0)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("market_median", models.PositiveBigIntegerField(default=0)),
                ("predicted_sale_price", models.PositiveBigIntegerField(blank=True, null=True)),
                ("acquisition_cost", models.PositiveBigIntegerField(default=0)),
                ("shipping_cost_estimate", models.PositiveBigIntegerField(default=0)),
                ("packaging_cost_estimate", models.PositiveBigIntegerField(default=0)),
                ("other_cost_estimate", models.PositiveBigIntegerField(default=0)),
                (
                    "fee_rate",
                    models.DecimalField(decimal_places=5, default=Decimal("0.10"), max_digits=6),
                ),
                ("target_profit", models.PositiveBigIntegerField(default=0)),
                ("note", models.TextField(blank=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inventory_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seller_listings",
                        to="Main.inventoryitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "-pk"),
            },
        ),
        migrations.CreateModel(
            name="SellerListingSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("current_price", models.PositiveBigIntegerField()),
                ("bidding", models.PositiveIntegerField()),
                ("remaining_seconds", models.PositiveBigIntegerField(null=True)),
                ("market_median", models.PositiveBigIntegerField()),
                ("predicted_sale_price", models.PositiveBigIntegerField()),
                ("estimated_fee", models.PositiveBigIntegerField()),
                ("estimated_profit", models.BigIntegerField()),
                ("calculation_inputs", models.JSONField(default=dict)),
                ("observed_status", models.CharField(max_length=20)),
                ("observed_at", models.DateTimeField(db_index=True)),
                (
                    "seller_listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="Main.sellerlisting",
                    ),
                ),
            ],
            options={
                "ordering": ("-observed_at", "-pk"),
            },
        ),
        migrations.AddIndex(
            model_name="sellerlisting",
            index=models.Index(
                fields=["user", "status", "-updated_at"], name="seller_owner_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sellerlisting",
            index=models.Index(fields=["user", "ends_at"], name="seller_owner_end_idx"),
        ),
        migrations.AddConstraint(
            model_name="sellerlisting",
            constraint=models.UniqueConstraint(
                fields=("user", "external_listing_id"), name="seller_owner_external_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="sellerlisting",
            constraint=models.UniqueConstraint(
                fields=("user", "url"), name="seller_owner_url_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="sellerlisting",
            constraint=models.CheckConstraint(
                condition=models.Q(("fee_rate__gte", 0), ("fee_rate__lte", 1)),
                name="seller_fee_rate_range",
            ),
        ),
        migrations.AddIndex(
            model_name="sellerlistingsnapshot",
            index=models.Index(
                fields=["seller_listing", "-observed_at"], name="seller_snapshot_time_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sellerlistingsnapshot",
            constraint=models.UniqueConstraint(
                fields=("seller_listing", "observed_at"), name="seller_snapshot_observed_unique"
            ),
        ),
    ]
