# Generated by Django 6.1 on 2026-09-05 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0017_seller_listing_phase3b"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="purchase_decision",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="sellerlisting",
            name="missing_cost_fields",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="sellerlisting",
            name="purchase_decision",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="sellerlisting",
            name="purchase_shipping_cost",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="sellerlistingsnapshot",
            name="estimated_fee",
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="sellerlistingsnapshot",
            name="estimated_profit",
            field=models.BigIntegerField(null=True),
        ),
        migrations.CreateModel(
            name="CostSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("assumptions", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("snapshot", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "watch_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_decisions",
                        to="Main.watchitem",
                    ),
                ),
            ],
            options={
                "ordering": ("-pk",),
            },
        ),
    ]
