# Generated by Django 6.1 on 2026-09-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("Main", "0018_purchase_budget_phase3c")]

    operations = [
        migrations.CreateModel(
            name="SaleRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sale_price", models.PositiveBigIntegerField()),
                ("actual_fee", models.PositiveBigIntegerField(default=0)),
                ("actual_shipping_cost", models.PositiveBigIntegerField(default=0)),
                ("actual_packaging_cost", models.PositiveBigIntegerField(default=0)),
                ("actual_other_cost", models.PositiveBigIntegerField(default=0)),
                ("sold_at", models.DateTimeField()),
                ("confirmed_profit", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seller_listing",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_record",
                        to="Main.sellerlisting",
                    ),
                ),
            ],
            options={"ordering": ("-sold_at", "-pk")},
        )
    ]
