# Generated by Django 6.1 on 2026-09-09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0019_sale_record_phase4"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=40)),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("target_url", models.CharField(blank=True, max_length=1000)),
                ("source_type", models.CharField(max_length=40)),
                ("source_id", models.BigIntegerField(blank=True, null=True)),
                ("dedupe_key", models.CharField(max_length=255)),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("read_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-pk"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "dedupe_key"),
                        name="unique_user_notification_dedupe",
                    )
                ],
            },
        )
    ]
