# Generated by Django 6.1 on 2026-09-10 00:08

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0020_notification_phase5"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("price_below", "価格が指定額以下"),
                            ("median_discount", "相場との差が指定率以上"),
                            ("ending_soon", "終了までの時間が指定分以下"),
                            ("low_bids", "入札数が指定数以下"),
                            ("buy_score", "買い時点数が指定値以上"),
                            ("new_listing", "新着候補"),
                            ("within_budget", "購入上限内"),
                            ("bid_stalled", "入札停滞"),
                            ("ending_without_bids", "入札なしで終了間近"),
                            ("loss_risk", "赤字見込み"),
                            ("target_profit", "目標利益到達"),
                            ("market_decline", "相場下落"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("threshold_value", models.DecimalField(decimal_places=4, max_digits=18)),
                ("is_enabled", models.BooleanField(db_index=True, default=True)),
                ("cooldown_minutes", models.PositiveIntegerField(default=60)),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "saved_search",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_rules",
                        to="Main.savedsearch",
                    ),
                ),
                (
                    "seller_listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_rules",
                        to="Main.sellerlisting",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "watch_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_rules",
                        to="Main.watchitem",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "-pk"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("saved_search__isnull", False),
                                ("seller_listing__isnull", True),
                                ("watch_item__isnull", True),
                            ),
                            models.Q(
                                ("saved_search__isnull", True),
                                ("seller_listing__isnull", True),
                                ("watch_item__isnull", False),
                            ),
                            models.Q(
                                ("saved_search__isnull", True),
                                ("seller_listing__isnull", False),
                                ("watch_item__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="alert_rule_exactly_one_target",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("cooldown_minutes__gte", 1)),
                        name="alert_rule_positive_cooldown",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("threshold_value__gte", Decimal("0"))),
                        name="alert_rule_nonnegative_threshold",
                    ),
                ],
            },
        ),
    ]
