# Generated by Django 6.1 on 2026-09-10

from django.db import migrations, models


def copy_inventory_category(apps, schema_editor):
    SaleRecord = apps.get_model("Main", "SaleRecord")
    for record in SaleRecord.objects.select_related("seller_listing__inventory_item").iterator():
        inventory = record.seller_listing.inventory_item
        if inventory and inventory.category:
            record.category = inventory.category
            record.save(update_fields=("category",))


class Migration(migrations.Migration):
    dependencies = [("Main", "0021_alert_rules_phase6")]

    operations = [
        migrations.AddField(
            model_name="salerecord",
            name="category",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.RunPython(copy_inventory_category, migrations.RunPython.noop),
    ]
