-- Systema application schema for PostgreSQL 16+
-- Prerequisite: Django's auth migrations have created public.auth_user.
-- This script intentionally creates only the current Main application tables.

BEGIN;

DO $$
BEGIN
    IF to_regclass('public.auth_user') IS NULL THEN
        RAISE EXCEPTION 'public.auth_user does not exist; run Django auth migrations first';
    END IF;
END
$$;

CREATE TABLE "Main_errorlog" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "error_code" varchar(50) NOT NULL,
    "error_message" text NOT NULL,
    "timestamp" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "file_path" varchar(255) NOT NULL DEFAULT '',
    "line_number" integer NULL
);

CREATE TABLE "Main_searchrun" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "session_key" varchar(40) NOT NULL DEFAULT '',
    "keyword" varchar(255) NOT NULL,
    "search_type" varchar(20) NOT NULL DEFAULT 'closed',
    "item_count" integer NOT NULL DEFAULT 0,
    "succeeded" boolean NOT NULL DEFAULT true,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "user_id" integer NULL,
    CONSTRAINT "Main_searchrun_item_count_nonnegative"
        CHECK ("item_count" >= 0),
    CONSTRAINT "Main_searchrun_search_type_valid"
        CHECK ("search_type" IN ('closed', 'current', 'target', 'prediction')),
    CONSTRAINT "Main_searchrun_user_id_fk"
        FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id")
        ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE "Main_scraping" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SearchWord" text NOT NULL,
    "SearchDay" text NOT NULL,
    "Bidding" text NOT NULL,
    "EndPrice" integer NOT NULL,
    "StartPrice" integer NOT NULL,
    "Name" text NOT NULL,
    "URL" text NOT NULL,
    "search_run_id" bigint NULL,
    CONSTRAINT "Main_scraping_search_run_id_fk"
        FOREIGN KEY ("search_run_id") REFERENCES "Main_searchrun" ("id")
        ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE "Main_searchwordlog" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "word" varchar(255) NOT NULL,
    "searched_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "session_key" varchar(40) NOT NULL DEFAULT '',
    "user_id" integer NULL,
    CONSTRAINT "Main_searchwordlog_user_id_fk"
        FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id")
        ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE "Main_watchitem" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" text NOT NULL,
    "url" varchar(1000) NOT NULL,
    "search_keyword" varchar(255) NOT NULL DEFAULT '',
    "current_price" bigint NOT NULL DEFAULT 0,
    "added_price" bigint NOT NULL DEFAULT 0,
    "bidding" integer NOT NULL DEFAULT 0,
    "remaining_time" varchar(100) NOT NULL DEFAULT '',
    "condition" varchar(20) NOT NULL DEFAULT 'unknown',
    "condition_label" varchar(50) NOT NULL DEFAULT U&'\672A\5206\985E',
    "market_median" bigint NOT NULL DEFAULT 0,
    "buy_status" varchar(30) NOT NULL DEFAULT 'insufficient',
    "buy_label" varchar(50) NOT NULL DEFAULT U&'\5224\5B9A\6750\6599\4E0D\8DB3',
    "buy_score" smallint NOT NULL DEFAULT 0,
    "buy_reason" text NOT NULL DEFAULT '',
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_checked_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "user_id" integer NULL,
    "session_key" varchar(40) NOT NULL DEFAULT '',
    CONSTRAINT "Main_watchitem_current_price_nonnegative" CHECK ("current_price" >= 0),
    CONSTRAINT "Main_watchitem_added_price_nonnegative" CHECK ("added_price" >= 0),
    CONSTRAINT "Main_watchitem_bidding_nonnegative" CHECK ("bidding" >= 0),
    CONSTRAINT "Main_watchitem_market_median_nonnegative" CHECK ("market_median" >= 0),
    CONSTRAINT "Main_watchitem_buy_score_range" CHECK ("buy_score" BETWEEN 0 AND 32767),
    CONSTRAINT "Main_watchitem_user_id_fk"
        FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id")
        ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX "Main_searchrun_session_key_idx" ON "Main_searchrun" ("session_key");
CREATE INDEX "Main_searchrun_keyword_idx" ON "Main_searchrun" ("keyword");
CREATE INDEX "Main_searchrun_created_at_idx" ON "Main_searchrun" ("created_at");
CREATE INDEX "Main_searchrun_user_id_idx" ON "Main_searchrun" ("user_id");

CREATE INDEX "Main_scraping_search_run_id_idx" ON "Main_scraping" ("search_run_id");

CREATE INDEX "Main_searchwordlog_word_idx" ON "Main_searchwordlog" ("word");
CREATE INDEX "Main_searchwordlog_session_key_idx" ON "Main_searchwordlog" ("session_key");
CREATE INDEX "Main_searchwordlog_user_id_idx" ON "Main_searchwordlog" ("user_id");

CREATE INDEX "Main_watchitem_buy_status_idx" ON "Main_watchitem" ("buy_status");
CREATE INDEX "Main_watchitem_session_key_idx" ON "Main_watchitem" ("session_key");
CREATE INDEX "Main_watchitem_user_id_idx" ON "Main_watchitem" ("user_id");

CREATE UNIQUE INDEX "unique_user_watch_url"
    ON "Main_watchitem" ("user_id", "url")
    WHERE "user_id" IS NOT NULL;

CREATE UNIQUE INDEX "unique_session_watch_url"
    ON "Main_watchitem" ("session_key", "url")
    WHERE "user_id" IS NULL AND "session_key" <> '';

COMMIT;

-- Verification (expected result: five rows)
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_name IN (
      'Main_errorlog',
      'Main_searchrun',
      'Main_scraping',
      'Main_searchwordlog',
      'Main_watchitem'
  )
ORDER BY table_name;
